//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int courseid { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string hours { get; set; }
        public string abbrev { get; set; }
    }
}
