//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class offeredcourse
    {
        public int offid { get; set; }
        public Nullable<int> secid { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> teacherid { get; set; }
    }
}
