//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vscheduleEntities : DbContext
    {
        public vscheduleEntities()
            : base("name=vscheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<day> days { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<slottype> slottypes { get; set; }
        public virtual DbSet<vschedule> vschedules { get; set; }
        public virtual DbSet<vslottype> vslottypes { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<offeredcourse> offeredcourses { get; set; }
        public virtual DbSet<slot> slots { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
    }
}
