//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vschedule
    {
        public int schid { get; set; }
        public Nullable<int> offid { get; set; }
        public int teacherid { get; set; }
        public string teachername { get; set; }
        public int courseid { get; set; }
        public string title { get; set; }
        public string sectionid { get; set; }
        public string sectionname { get; set; }
        public string programid { get; set; }
        public Nullable<int> slotid { get; set; }
        public int dayid { get; set; }
        public string dayname { get; set; }
        public string duration { get; set; }
        public Nullable<int> slotno { get; set; }
        public int slottypeid { get; set; }
        public int subslotid { get; set; }
        public Nullable<int> occupied { get; set; }
        public int roomid { get; set; }
        public string roomno { get; set; }
        public string campus { get; set; }
        public string roomtype { get; set; }
    }
}
